### PR TITLE
add LABEL instruction

### PR DESCRIPTION
**Pull request by blindgaenger**
Alright, here is the pendant pull-request for asbjornenge/Docker.tmbundle#3.

### CODE REVIEW

**Comment by asbjornenge** [comment]
Thanks again :smile:

**Comment by princemaple** [comment]
@asbjornenge I made a new release.

**Comment by blindgaenger** [comment]
upgrading sublime package … aaaaaand it works! :bow:

label

**Comment by princemaple** [comment]
:boom:

**Comment by asbjornenge** [comment]
You guuuys are awesome!! :grin: :rocket: Very cool :smile_cat:

**Pull request merged**
